### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'layer'

### ISSUE THREAD

**Issue by 20170702102** [percent4/Keras_R_BERT#1]
C:\developmentTool\Anaconda\envs\rbert\python.exe C:/project/pythonProject/bba/Keras_R_BERT/model_train.py
C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
begin data processing...
WARNING:tensorflow:From C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

finish data processing!
WARNING:tensorflow:From C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\keras\initializers.py:119: calling RandomUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Traceback (most recent call last):
  File "C:/project/pythonProject/bba/Keras_R_BERT/model_train.py", line 137, in <module>
    model = create_cls_model(len(labels))
  File "C:/project/pythonProject/bba/Keras_R_BERT/model_train.py", line 102, in create_cls_model
    model = RBERT(BERT_CONFIG_PATH, BERT_CHECKPOINT_PATH, MAX_LEN, num_labels).create_model()
  File "C:\project\pythonProject\bba\Keras_R_BERT\model.py", line 23, in create_model
    bert_model = load_trained_model_from_checkpoint(self.config_path, self.checkpoint_path, seq_len=None)
  File "C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\keras_bert\loader.py", line 169, in load_trained_model_from_checkpoint
    **kwargs)
  File "C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\keras_bert\loader.py", line 58, in build_model_from_config
    **kwargs)
  File "C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\keras_bert\bert.py", line 84, in get_model
    dropout_rate=dropout_rate,
  File "C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\keras_bert\layers\embedding.py", line 56, in get_embedding
    )(embed_layer)
  File "C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 663, in __call__
    inputs, outputs, args, kwargs)
  File "C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1708, in _set_connectivity_metadata_
    input_tensors=inputs, output_tensors=outputs, arguments=kwargs)
  File "C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1795, in _add_inbound_node
    input_tensors)
  File "C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\util\nest.py", line 515, in map_structure
    structure[0], [func(*x) for x in entries],
  File "C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\util\nest.py", line 515, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1794, in <lambda>
    inbound_layers = nest.map_structure(lambda t: t._keras_history.layer,
AttributeError: 'tuple' object has no attribute 'layer'

**Comment by 20170702102** [comment]
> C:\developmentTool\Anaconda\envs\rbert\python.exe C:/project/pythonProject/bba/Keras_R_BERT/model_train.py C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint8 = np.dtype([("qint8", np.int8, 1)]) C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_quint8 = np.dtype([("quint8", np.uint8, 1)]) C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint16 = np.dtype([("qint16", np.int16, 1)]) C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_quint16 = np.dtype([("quint16", np.uint16, 1)]) C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint32 = np.dtype([("qint32", np.int32, 1)]) C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. np_resource = np.dtype([("resource", np.ubyte, 1)]) C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint8 = np.dtype([("qint8", np.int8, 1)]) C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_quint8 = np.dtype([("quint8", np.uint8, 1)]) C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint16 = np.dtype([("qint16", np.int16, 1)]) C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_quint16 = np.dtype([("quint16", np.uint16, 1)]) C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint32 = np.dtype([("qint32", np.int32, 1)]) C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. np_resource = np.dtype([("resource", np.ubyte, 1)]) Using TensorFlow backend. begin data processing... WARNING:tensorflow:From C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.
> 
> finish data processing! WARNING:tensorflow:From C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.
> 
> WARNING:tensorflow:From C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\keras\initializers.py:119: calling RandomUniform.**init** (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version. Instructions for updating: Call initializer instance with the dtype argument instead of passing it to the constructor Traceback (most recent call last): File "C:/project/pythonProject/bba/Keras_R_BERT/model_train.py", line 137, in model = create_cls_model(len(labels)) File "C:/project/pythonProject/bba/Keras_R_BERT/model_train.py", line 102, in create_cls_model model = RBERT(BERT_CONFIG_PATH, BERT_CHECKPOINT_PATH, MAX_LEN, num_labels).create_model() File "C:\project\pythonProject\bba\Keras_R_BERT\model.py", line 23, in create_model bert_model = load_trained_model_from_checkpoint(self.config_path, self.checkpoint_path, seq_len=None) File "C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\keras_bert\loader.py", line 169, in load_trained_model_from_checkpoint **kwargs) File "C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\keras_bert\loader.py", line 58, in build_model_from_config **kwargs) File "C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\keras_bert\bert.py", line 84, in get_model dropout_rate=dropout_rate, File "C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\keras_bert\layers\embedding.py", line 56, in get_embedding )(embed_layer) File "C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 663, in **call** inputs, outputs, args, kwargs) File "C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1708, in _set_connectivity_metadata_ input_tensors=inputs, output_tensors=outputs, arguments=kwargs) File "C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1795, in _add_inbound_node input_tensors) File "C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\util\nest.py", line 515, in map_structure structure[0], [func(*x) for x in entries], File "C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\util\nest.py", line 515, in structure[0], [func(*x) for x in entries], File "C:\developmentTool\Anaconda\envs\rbert\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1794, in inbound_layers = nest.map_structure(lambda t: t._keras_history.layer, AttributeError: 'tuple' object has no attribute 'layer'

我把keras_bert==0.83.0替换成keras_bert==0.89解决了这个问题

**Comment by percent4** [comment]
主要是Python第三方模块版本问题，可以参考requirements.txt文件
